AllCops:
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Naming/MethodParameterName:
  Enabled: false

Style/Documentation:
  Enabled: false
